/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}


repositories {
    mavenCentral()
    flatDir {
        dirs("libs")
    }
}

dependencies {
    implementation(platform("software.amazon.awssdk:bom:2.31.38"))
    implementation("software.amazon.awssdk:bedrockruntime")
    implementation("software.amazon.awssdk:netty-nio-client")
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation("org.json:json:20231013")
    implementation("io.reactivex.rxjava3:rxjava:3.1.8")
    implementation("io.projectreactor:reactor-core:3.6.2")
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.20.0")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation(platform("org.eclipse.jetty:jetty-bom:11.0.25"))
    implementation("org.eclipse.jetty:jetty-server")
    implementation("org.eclipse.jetty:jetty-servlet")
    implementation("org.eclipse.jetty:jetty-webapp")
    implementation("org.eclipse.jetty.websocket:websocket-jetty-server")
    implementation("org.eclipse.jetty.websocket:websocket-jetty-client")
    implementation("org.eclipse.jetty:jetty-util")
    implementation("org.eclipse.jetty:jetty-http")
    implementation("org.eclipse.jetty:jetty-io")
    implementation("jakarta.servlet:jakarta.servlet-api:5.0.0")
    implementation("org.eclipse.jetty:jetty-security")
    implementation("org.eclipse.jetty:jetty-annotations")
    implementation("org.eclipse.jetty:jetty-plus")
    implementation("org.eclipse.jetty:jetty-xml")
    implementation("org.eclipse.jetty.websocket:websocket-servlet")
    implementation("org.eclipse.jetty.websocket:websocket-core-server")
    implementation("org.eclipse.jetty.websocket:websocket-core-client")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2")
    compileOnly("org.projectlombok:lombok:1.18.30") // Use the latest version
    annotationProcessor("org.projectlombok:lombok:1.18.30")

    testImplementation(libs.junit.jupiter)
    testImplementation("org.mockito:mockito-core:5.8.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.8.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "org.example.BedrockInitiateClient"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.withType<JavaCompile> {
    options.annotationProcessorPath = configurations.annotationProcessor.get()
}

